version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  autobooker:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.3-browsers


    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install and run
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 autobooker.py
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

